This script is to generate the class labels for the partwhole dataset

In [8]:
import os
from tqdm import tqdm
import pandas as pd

In [3]:
# Class names of every image
fulldata_path = r"/home/c/choton/beemachine/datasets/Bee_Full_Body_Segments/Images"
DATA_DIR = r"/home/c/choton/beemachine/datasets/Beemachine_Partwhole_v1/"

# Get list of classes
classes = os.listdir(fulldata_path)
species_dict = {}

for c in classes:
    images_path = os.path.join(fulldata_path, c)
    images = os.listdir(images_path)
    for image in images:
        image_name = image[:-4]
        species_dict[image_name] = c
image_names = list(species_dict.keys())
len(image_names)

8029

In [4]:
train_imgs_path = os.path.join(DATA_DIR, 'train', 'images')
val_imgs_path = os.path.join(DATA_DIR, 'valid', 'images')
test_imgs_path = os.path.join(DATA_DIR, 'test', 'images')
train_images = os.listdir(train_imgs_path)
val_images = os.listdir(val_imgs_path)
test_images = os.listdir(test_imgs_path)
print(f"Images in dataset, train: {len(train_images)}, val: {len(val_images)}, test: {len(test_images)}")

Images in dataset, train: 23903, val: 2812, test: 1407

In [6]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in train_images:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)

100%|██████████| 8029/8029 [00:59<00:00, 134.89it/s]

23911

In [14]:
train_dict = {'images': train_images}
train_df = pd.DataFrame(train_dict)
train_df['species'] = train_df['images'].map(species_y)
train_df

                                                  images            species
0      BBW_Bombus_appositus_30662_b9adbe76-8e39-462e-...   Bombus_appositus
1      BBW_Bombus_appositus_44449_5f8fbe08-ce2f-4f0a-...   Bombus_appositus
2      309QLSWQT0IKUKSKEKRKPKRKPKZKWKRKV0NQLS1QJ09QB0...   Bombus_impatiens
3      6QC05QO0NQNK7KTKQK2KRKPKHK2KHKUKGK30MKTK8KY08Q...   Bombus_sitkensis
4      5LVZXLBZHLHRMHDH8HBHXHDHMHVHHLCHRL8ZKLEZ0LPZZL...      Bombus_huntii
...                                                  ...                ...
23898  Bombus_bifarius_GBIF_iNat_3383889221_4-jpg_jpg...    Bombus_bifarius
23899  1KMKDKXKUKUQT0PQA09QLSVQY05KVKZKV0KKUK0KB00KO0...   Bombus_insularis
23900  BBB_Bombus_affinis_664-2_1_jpg.rf.603dd9325446...     Bombus_affinis
23901  Bombus_bellicosus_GBIF_iNat_2992715809_1-jpg_j...  Bombus_bellicosus
23902  Bombus_bifarius_53119799_2_1_jpg.rf.3a590c7d27...    Bombus_bifarius

[23903 rows x 2 columns]

In [15]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in val_images:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)

100%|██████████| 8029/8029 [00:07<00:00, 1136.92it/s]

2815

In [16]:
valid_dict = {'images': val_images}
valid_df = pd.DataFrame(valid_dict)
valid_df['species'] = valid_df['images'].map(species_y)
valid_df

                                                 images            species
0     Bombus_bifarius_iNat_93444986_1-jpg_jpg.rf.524...    Bombus_bifarius
1     4LBZMLVZZLZRXHCHGHRRNHJHPHJH7L4Z0LDHKL6ZRLVHKL...      Bombus_mixtus
2     Bombus_dahlbomii_GBIF_iNat_1702453884_1-jpg_jp...   Bombus_dahlbomii
3     2KRKWKLKOK8QHSNQHS2QD08QT08QPK4QUKGQV00KCKVQY0...   Bombus_insularis
4     BBW_Bombus_crotchii_39538_947c1d25-a6df-4698-b...    Bombus_crotchii
...                                                 ...                ...
2807  BBW_Bombus_vandykei_16978_c5f03ca4-c6f9-4dc7-a...    Bombus_vandykei
2808  BBW_Bombus_appositus_30950_fd7c39cf-0217-4e9a-...   Bombus_appositus
2809  Bombus_alpinus_iNat_54101328_1-jpg_jpg.rf.b38b...     Bombus_alpinus
2810  BBW_Bombus_appositus_45485_0f815f9c-b8d2-46bd-...   Bombus_appositus
2811  Bombus_campestris_iNat_29014902_1-jpg_jpg.rf.b...  Bombus_campestris

[2812 rows x 2 columns]

In [17]:
count = 0
species_y = {}
for image_n in tqdm(image_names):
    for image_y in test_images:
        # print(image_n)
        # print(image_y)
        # input()
        image_nx = image_n.replace("._", "-_")
        image_nx = image_nx.replace(".jpg", "")
        if image_nx in image_y:
            count += 1
            species_y[image_y] = species_dict[image_n]
print(count)

100%|██████████| 8029/8029 [00:03<00:00, 2277.69it/s]

1408

In [18]:
test_dict = {'images': test_images}
test_df = pd.DataFrame(test_dict)
test_df['species'] = test_df['images'].map(species_y)
test_df

                                                 images              species
0     BBW_Bombus_appositus_24367_debb9cc0-da33-40d5-...     Bombus_appositus
1     Bombus_bellicosus_GBIF_iNat_3301925741_1-jpg_j...    Bombus_bellicosus
2     Bombus_bicoloratus_iNat_54623311_1-jpg_jpg.rf....   Bombus_bicoloratus
3     BBB_Bombus_affinis_2700-1_1_jpg.rf.94cd0582265...       Bombus_affinis
4     9HHRPHZRIHVZRL4ZXL9ZILAZ4LAZILLRGLUZIL3HXHFHEH...     Bombus_ternarius
...                                                 ...                  ...
1402  BBB_Bombus_affinis_1830-3_1_jpg.rf.db65156b0b5...       Bombus_affinis
1403  BBB_Bombus_vagans_227-1_1_jpg.rf.b103432e2c950...        Bombus_vagans
1404  BBW_Bombus_appositus_34400_ff40fae5-166a-4ca3-...     Bombus_appositus
1405  BBW_Bombus_appositus_45002_568eeb5c-0875-4c1a-...     Bombus_appositus
1406  BBW_Bombus_vosnesenskii_482_52f1dd3d-4b74-4acd...  Bombus_vosnesenskii

[1407 rows x 2 columns]

In [ ]:
train_df_path = os.path.join(DATA_DIR, 'train_labels.csv')
val_df_path = os.path.join(DATA_DIR, 'val_labels.csv')
test_df_path = os.path.join(DATA_DIR, 'test_labels.csv')
train_df.to_csv(train_df_path, index=False)
valid_df.to_csv(val_df_path, index=False)
test_df.to_csv(test_df_path, index=False)